[package]
name = 'wasmer/hello-world'
version = '0.1.7'
description = 'Hello world package for wasmer; test your wasmer installation'
readme = 'README.md'
repository = "https://github.com/ayys/hello"
license = "MIT"

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = 'hello'
source = 'target/wasm32-wasmer-wasi/release/hello.wasm'
abi = 'wasi'

[module.interfaces]
wasi = '0.1.0-unstable'

[[command]]
name = 'hello'
module = 'hello'
runner = 'wasi'
